# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "protoc-gen-hb-grpc-gateway"

# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
