# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "protoc-gen-hb-grpc-gateway"

# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
