// Code generated by protoc-gen-hb-grpc-gateway. DO NOT EDIT.
// source: proto/example/example.proto

/*
Package go_micro_srv_example is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package go_micro_srv_example

import (
	"github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/httprule"
	"github.com/hb-go/grpc-contrib/registry"
)

var (
	route_Example_Call_0 = registry.Binding{
		Method: "POST",
		PathTmpl: &httprule.Template{
			Version: 1,
			OpCodes: []int{2, 0, 2, 1, 2, 2},
			Pool:    []string{"v1", "example", "call"},
			Verb:    "",
		},
		AssumeColonVerb: true,
	}

	route_Example_Call_1 = registry.Binding{
		Method: "GET",
		PathTmpl: &httprule.Template{
			Version: 1,
			OpCodes: []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3},
			Pool:    []string{"v1", "example", "call", "name"},
			Verb:    "",
		},
		AssumeColonVerb: true,
	}
)

var GatewayServiceExample = registry.Service{
	Name: _Example_serviceDesc.ServiceName,
	Methods: []*registry.Method{
		&registry.Method{
			Name: "Call",
			Bindings: []*registry.Binding{
				&route_Example_Call_0,
				&route_Example_Call_1,
			},
		},

		&registry.Method{
			Name:     "Stream",
			Bindings: []*registry.Binding{},
		},

		&registry.Method{
			Name:     "PingPong",
			Bindings: []*registry.Binding{},
		},
	},
}
