// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/example/example.proto

/*
Package go_micro_srv_example is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package go_micro_srv_example

import (
	"github.com/hb-chen/gateway/registry"
)

var (
	route_Example_Call_0 = registry.Route{
		Method: "POST",
		Pattern: &registry.Pattern{
			Version:         1,
			Ops:             []int{2, 0, 2, 1, 2, 2},
			Pool:            []string{"v1", "example", "call"},
			Verb:            "",
			AssumeColonVerb: true,
		},
	}

	route_Example_Call_1 = registry.Route{
		Method: "GET",
		Pattern: &registry.Pattern{
			Version:         1,
			Ops:             []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3},
			Pool:            []string{"v1", "example", "call", "name"},
			Verb:            "",
			AssumeColonVerb: true,
		},
	}
)

var RegistryServiceExample = registry.Service{
	Name: _Example_serviceDesc.ServiceName,
	Methods: []*registry.Method{
		&registry.Method{
			Name: "Call",
			Routes: []*registry.Route{
				&route_Example_Call_0,
				&route_Example_Call_1,
			},
		},

		&registry.Method{
			Name:   "Stream",
			Routes: []*registry.Route{},
		},

		&registry.Method{
			Name:   "PingPong",
			Routes: []*registry.Route{},
		},
	},
}
