// Code generated by protoc-gen-hb-grpc. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	registry "github.com/hb-go/grpc-contrib/registry"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// gRPC Registry
// github.com/hb-go/grpc-contrib/registry

// Example registry
func TargetExample(opts ...registry.Option) string {
	return registry.NewTarget(&_Example_serviceDesc, opts...)
}

func RegisterExample(opts ...registry.Option) error {
	return registry.Register(&_Example_serviceDesc, opts...)
}

func DeregisterExample(opts ...registry.Option) {
	registry.Deregister(&_Example_serviceDesc, opts...)
}
