// Code generated by protoc-gen-hb-grpc-gateway. DO NOT EDIT.
// source: example/proto/service.proto

/*
Package proto is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package proto

import (
	"github.com/hb-chen/gateway/registry"
)

var (
	route_ExampleService_Call_0 = registry.Route{
		Method: "POST",
		Pattern: &registry.Pattern{
			Version:         1,
			Ops:             []int{2, 0, 2, 1, 2, 2},
			Pool:            []string{"v1", "example", "call"},
			Verb:            "",
			AssumeColonVerb: true,
		},
	}

	route_ExampleService_Call_1 = registry.Route{
		Method: "GET",
		Pattern: &registry.Pattern{
			Version:         1,
			Ops:             []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3},
			Pool:            []string{"v1", "example", "call", "name"},
			Verb:            "",
			AssumeColonVerb: true,
		},
	}
)

var GatewayServiceExampleService = registry.Service{
	Name: _ExampleService_serviceDesc.ServiceName,
	Methods: []*registry.Method{
		&registry.Method{
			Name: "Call",
			Routes: []*registry.Route{
				&route_ExampleService_Call_0,
				&route_ExampleService_Call_1,
			},
		},
	},
}
