name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: Code
      uses: actions/checkout@v1
    - name: Intsall Golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b . latest
    - name: Lint
      run: ./golangci-lint run ./...
    - name: Run coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

  test:
    #needs: Lint
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest,ubuntu-latest]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: Code
      uses: actions/checkout@v1
    - name: Go Get dependencies
      run: go get -v -t -d ./...
    - name: Go Test
      run: go test -race -cover -v ./...
    - name: Run coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      if: matrix.os == 'ubuntu-latest'
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
      if: matrix.os == 'ubuntu-latest'
